name: triathlon_app
description: "Application d'entraînement Triathlon"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  path_provider: ^2.1.0
  audioplayers: ^5.2.0
  intl: ^0.18.0  # <-- DÉCOMMENTER CETTE LIGNE
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/