name: Build iOS App

on:
  push:
    branches: [main]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'

      - name: Fix iOS structure
        run: |
          flutter clean
          flutter create --platforms=ios .

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Install iOS dependencies
        run: |
          cd ios
          pod install --repo-update

      - name: Build IPA
        run: flutter build ipa --debug --no-codesign

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: triathlon-app-ipa
          path: build/ios/ipa/*.ipa